# Generated by Django 4.2.30 on 2026-04-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], default='DEBIT', max_length=20)),
                ('merchant', models.CharField(max_length=255)),
                ('merchant_category', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_country', models.CharField(blank=True, max_length=3, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FLAGGED', 'Flagged'), ('BLOCKED', 'Blocked'), ('INVESTIGATING', 'Under Investigation')], default='PENDING', max_length=20)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('rule_triggers', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='transaction_user_id_8a9c6d_idx'), models.Index(fields=['status', '-timestamp'], name='transaction_status_da3101_idx'), models.Index(fields=['risk_level', '-timestamp'], name='transaction_risk_le_3d8ef5_idx'), models.Index(fields=['timestamp'], name='transaction_timesta_07633a_idx')],
            },
        ),
    ]
