# Generated by Django 4.2.30 on 2026-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
