# Generated by Django 4.2.30 on 2026-04-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cluster_id', models.IntegerField()),
                ('avg_transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_transaction_frequency', models.FloatField()),
                ('total_users', models.IntegerField(default=0)),
                ('avg_risk_score', models.FloatField(default=50.0)),
                ('characteristics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_segments',
                'ordering': ['cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(default=50.0)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('last_transaction_count', models.IntegerField(default=0)),
                ('last_24h_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_7d_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_transaction_frequency', models.FloatField(default=0)),
                ('segment', models.CharField(choices=[('PREMIUM', 'Premium'), ('REGULAR', 'Regular'), ('SUSPICIOUS', 'Suspicious'), ('HIGH_RISK', 'High Risk'), ('NEW', 'New User')], default='NEW', max_length=20)),
                ('transaction_count', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('flags', models.JSONField(default=dict)),
                ('last_flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('is_monitored', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.JSONField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behaviors',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['user', 'metric_name'], name='user_behavi_user_id_577c1a_idx')],
            },
        ),
    ]
